- name: Playbook to Install Packages
  hosts: localhost
  connection: local
    #- local
      #    - dev
      #    - prod
  tasks:
  - name: Install mariadb
    package:
      name:
        - mariadb-server
      state: present
